# Generated by Django 3.1.6 on 2021-02-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
