# Generated by Django 3.1.6 on 2021-02-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0005_pedido_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Ramo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
