# Generated by Django 3.1.6 on 2021-02-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0006_produto_ramo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='Ramo',
            field=models.CharField(max_length=25),
        ),
    ]
