# Generated by Django 3.1.6 on 2021-02-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0007_auto_20210224_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Código', models.IntegerField()),
                ('Descrição', models.TextField()),
                ('Ramo', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apdated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
