# Generated by Django 3.1.6 on 2021-04-29 13:19

import component.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0009_auto_20210428_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Nome',
            field=models.ForeignKey(on_delete=component.models.Produto1, to='component.produto'),
        ),
    ]
