# Generated by Django 3.1.6 on 2021-04-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0010_auto_20210429_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='component.produto'),
        ),
    ]
