# Generated by Django 3.1.6 on 2021-04-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0011_auto_20210429_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teste', to='component.pedido'),
            preserve_default=False,
        ),
    ]
