# Generated by Django 3.1.6 on 2021-04-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0012_produto_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='Pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='nomeProduto',
            field=models.ForeignKey( default=0,null=False, on_delete=django.db.models.deletion.CASCADE, related_name='teste', to='component.pedido'),
            preserve_default=False,
        ),
    ]
